language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 5.3
  - 7.0
  - 7.1
  - hhvm

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - PHPUNIT_BIN=vendor/bin/phpunit

matrix:
  include:
    - php: 5.3
      env: PHPUNIT_BIN=phpunit-4.8.phar
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1

install: if [ $PHPUNIT_BIN = vendor/bin/phpunit ]; then travis_retry composer install; fi

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - if [ $TRAVIS_PHP_VERSION = 5.3 ]; then wget https://phar.phpunit.de/phpunit-4.8.phar; fi

script: php $PHPUNIT_BIN
